// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: grpc/auction.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BidResponse_Status int32

const (
	BidResponse_SUCCESS   BidResponse_Status = 0
	BidResponse_FAIL      BidResponse_Status = 1
	BidResponse_EXCEPTION BidResponse_Status = 2
)

// Enum value maps for BidResponse_Status.
var (
	BidResponse_Status_name = map[int32]string{
		0: "SUCCESS",
		1: "FAIL",
		2: "EXCEPTION",
	}
	BidResponse_Status_value = map[string]int32{
		"SUCCESS":   0,
		"FAIL":      1,
		"EXCEPTION": 2,
	}
)

func (x BidResponse_Status) Enum() *BidResponse_Status {
	p := new(BidResponse_Status)
	*p = x
	return p
}

func (x BidResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BidResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_auction_proto_enumTypes[0].Descriptor()
}

func (BidResponse_Status) Type() protoreflect.EnumType {
	return &file_grpc_auction_proto_enumTypes[0]
}

func (x BidResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BidResponse_Status.Descriptor instead.
func (BidResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_grpc_auction_proto_rawDescGZIP(), []int{1, 0}
}

type BidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BidderId      string                 `protobuf:"bytes,1,opt,name=bidder_id,json=bidderId,proto3" json:"bidder_id,omitempty"`
	Amount        int32                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidRequest) Reset() {
	*x = BidRequest{}
	mi := &file_grpc_auction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidRequest) ProtoMessage() {}

func (x *BidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_auction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidRequest.ProtoReflect.Descriptor instead.
func (*BidRequest) Descriptor() ([]byte, []int) {
	return file_grpc_auction_proto_rawDescGZIP(), []int{0}
}

func (x *BidRequest) GetBidderId() string {
	if x != nil {
		return x.BidderId
	}
	return ""
}

func (x *BidRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type BidResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        BidResponse_Status     `protobuf:"varint,1,opt,name=status,proto3,enum=auction.BidResponse_Status" json:"status,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidResponse) Reset() {
	*x = BidResponse{}
	mi := &file_grpc_auction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidResponse) ProtoMessage() {}

func (x *BidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_auction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidResponse.ProtoReflect.Descriptor instead.
func (*BidResponse) Descriptor() ([]byte, []int) {
	return file_grpc_auction_proto_rawDescGZIP(), []int{1}
}

func (x *BidResponse) GetStatus() BidResponse_Status {
	if x != nil {
		return x.Status
	}
	return BidResponse_SUCCESS
}

func (x *BidResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultRequest) Reset() {
	*x = ResultRequest{}
	mi := &file_grpc_auction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultRequest) ProtoMessage() {}

func (x *ResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_auction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultRequest.ProtoReflect.Descriptor instead.
func (*ResultRequest) Descriptor() ([]byte, []int) {
	return file_grpc_auction_proto_rawDescGZIP(), []int{2}
}

type ResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HighestBid    int32                  `protobuf:"varint,1,opt,name=highest_bid,json=highestBid,proto3" json:"highest_bid,omitempty"`
	WinnerId      string                 `protobuf:"bytes,2,opt,name=winner_id,json=winnerId,proto3" json:"winner_id,omitempty"`
	IsOver        bool                   `protobuf:"varint,3,opt,name=is_over,json=isOver,proto3" json:"is_over,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultResponse) Reset() {
	*x = ResultResponse{}
	mi := &file_grpc_auction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultResponse) ProtoMessage() {}

func (x *ResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_auction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultResponse.ProtoReflect.Descriptor instead.
func (*ResultResponse) Descriptor() ([]byte, []int) {
	return file_grpc_auction_proto_rawDescGZIP(), []int{3}
}

func (x *ResultResponse) GetHighestBid() int32 {
	if x != nil {
		return x.HighestBid
	}
	return 0
}

func (x *ResultResponse) GetWinnerId() string {
	if x != nil {
		return x.WinnerId
	}
	return ""
}

func (x *ResultResponse) GetIsOver() bool {
	if x != nil {
		return x.IsOver
	}
	return false
}

type SyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HighestBid    int32                  `protobuf:"varint,1,opt,name=highest_bid,json=highestBid,proto3" json:"highest_bid,omitempty"`
	WinnerId      string                 `protobuf:"bytes,2,opt,name=winner_id,json=winnerId,proto3" json:"winner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_grpc_auction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_auction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_grpc_auction_proto_rawDescGZIP(), []int{4}
}

func (x *SyncRequest) GetHighestBid() int32 {
	if x != nil {
		return x.HighestBid
	}
	return 0
}

func (x *SyncRequest) GetWinnerId() string {
	if x != nil {
		return x.WinnerId
	}
	return ""
}

type SyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ack           bool                   `protobuf:"varint,1,opt,name=ack,proto3" json:"ack,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_grpc_auction_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_auction_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_grpc_auction_proto_rawDescGZIP(), []int{5}
}

func (x *SyncResponse) GetAck() bool {
	if x != nil {
		return x.Ack
	}
	return false
}

var File_grpc_auction_proto protoreflect.FileDescriptor

const file_grpc_auction_proto_rawDesc = "" +
	"\n" +
	"\x12grpc/auction.proto\x12\aauction\"A\n" +
	"\n" +
	"BidRequest\x12\x1b\n" +
	"\tbidder_id\x18\x01 \x01(\tR\bbidderId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x05R\x06amount\"\x8a\x01\n" +
	"\vBidResponse\x123\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1b.auction.BidResponse.StatusR\x06status\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\".\n" +
	"\x06Status\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\b\n" +
	"\x04FAIL\x10\x01\x12\r\n" +
	"\tEXCEPTION\x10\x02\"\x0f\n" +
	"\rResultRequest\"g\n" +
	"\x0eResultResponse\x12\x1f\n" +
	"\vhighest_bid\x18\x01 \x01(\x05R\n" +
	"highestBid\x12\x1b\n" +
	"\twinner_id\x18\x02 \x01(\tR\bwinnerId\x12\x17\n" +
	"\ais_over\x18\x03 \x01(\bR\x06isOver\"K\n" +
	"\vSyncRequest\x12\x1f\n" +
	"\vhighest_bid\x18\x01 \x01(\x05R\n" +
	"highestBid\x12\x1b\n" +
	"\twinner_id\x18\x02 \x01(\tR\bwinnerId\" \n" +
	"\fSyncResponse\x12\x10\n" +
	"\x03ack\x18\x01 \x01(\bR\x03ack2\xb2\x01\n" +
	"\x0eAuctionService\x120\n" +
	"\x03Bid\x12\x13.auction.BidRequest\x1a\x14.auction.BidResponse\x129\n" +
	"\x06Result\x12\x16.auction.ResultRequest\x1a\x17.auction.ResultResponse\x123\n" +
	"\x04Sync\x12\x14.auction.SyncRequest\x1a\x15.auction.SyncResponseB\x1aZ\x18distributed-auction/grpcb\x06proto3"

var (
	file_grpc_auction_proto_rawDescOnce sync.Once
	file_grpc_auction_proto_rawDescData []byte
)

func file_grpc_auction_proto_rawDescGZIP() []byte {
	file_grpc_auction_proto_rawDescOnce.Do(func() {
		file_grpc_auction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_auction_proto_rawDesc), len(file_grpc_auction_proto_rawDesc)))
	})
	return file_grpc_auction_proto_rawDescData
}

var file_grpc_auction_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_grpc_auction_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_grpc_auction_proto_goTypes = []any{
	(BidResponse_Status)(0), // 0: auction.BidResponse.Status
	(*BidRequest)(nil),      // 1: auction.BidRequest
	(*BidResponse)(nil),     // 2: auction.BidResponse
	(*ResultRequest)(nil),   // 3: auction.ResultRequest
	(*ResultResponse)(nil),  // 4: auction.ResultResponse
	(*SyncRequest)(nil),     // 5: auction.SyncRequest
	(*SyncResponse)(nil),    // 6: auction.SyncResponse
}
var file_grpc_auction_proto_depIdxs = []int32{
	0, // 0: auction.BidResponse.status:type_name -> auction.BidResponse.Status
	1, // 1: auction.AuctionService.Bid:input_type -> auction.BidRequest
	3, // 2: auction.AuctionService.Result:input_type -> auction.ResultRequest
	5, // 3: auction.AuctionService.Sync:input_type -> auction.SyncRequest
	2, // 4: auction.AuctionService.Bid:output_type -> auction.BidResponse
	4, // 5: auction.AuctionService.Result:output_type -> auction.ResultResponse
	6, // 6: auction.AuctionService.Sync:output_type -> auction.SyncResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_grpc_auction_proto_init() }
func file_grpc_auction_proto_init() {
	if File_grpc_auction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_auction_proto_rawDesc), len(file_grpc_auction_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_auction_proto_goTypes,
		DependencyIndexes: file_grpc_auction_proto_depIdxs,
		EnumInfos:         file_grpc_auction_proto_enumTypes,
		MessageInfos:      file_grpc_auction_proto_msgTypes,
	}.Build()
	File_grpc_auction_proto = out.File
	file_grpc_auction_proto_goTypes = nil
	file_grpc_auction_proto_depIdxs = nil
}
